# Starter pipeline
# Start with a minimal pipeline that you can customoze to build and deploy your code
# Add steps that build, run tests, deploy, and more:

trigger:
 branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, World!
  displayName: 'Run a one line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo see https://aka.ms/yaml
  displayName: 'Run a multi-line script'
