# Demo spring application
# Testing this after adding new branch
# Pipeline Condition Test

trigger:
 branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Junit Stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Running Spring demo app unit test'
          - task: Maven@4
            inputs:
              azureSubscription: 'Azure subscription 1(6664a209-4f14-4fc3-92d7-597da7d890c4)'
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              allowBrokenSymlinks: false
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true

  - stage: 'BuildArtifact'
    displayName: 'BuildingArtifact'
    condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'))
    dependsOn: 'Junit'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'BuildingArtifact'
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Azure subscription 1(6664a209-4f14-4fc3-92d7-597da7d890c4)'
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '--no-transfer-progress'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(agent.builddirectory)/s/target'
              Contents: '*jar'
              TargetFolder: '$(build.artifactstagingdirectory)'
              CleanTargetFolder: true
              OverWrite: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'